name: Geoguessr CI

on: 
  push: 
    branches: 
      - master
      - feature/ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Install dependencies
        run: |
          go version
          go mod download
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build ./cmd/geoguessr
  deploy:
    runs-on: ubuntu-latest
    # Only run this workflow when "build" workflow succeeds
    needs: [build]
    # Only run this workflow if it is master branch on push event
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} 
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/watercooler-jams/geoguessr:latest
